### ISSUE TITLE
DeepCas problem

### ISSUE THREAD

**Issue by Sean0719** [MJQCPP/agar-front#2]
Hi, 

Sorry to ask question in here. For the tensorflow version of deepcas, how can i save the trained model, i try but i failed since i am a begginer of tensorflow. Could you give me some suggestions? Thanks.

**Comment by jiaqima** [comment]
Hi Sean,

That library is based on TF version 0.12.1, which is very outdated. Sorry I cannot easily tell how to save the model with the 0.12.1 API either. You can refer to https://github.com/tensorflow/tensorflow/tree/r0.12 to have a look at the documents there.
